/*
 * Copyright 2010-2019 JetBrains s.r.o. and Kotlin Project contributors. Use of this source code is governed
 * by the Apache 2.0 license that can be found in the license/LICENSE.txt file.
 */

// DO NOT EDIT MANUALLY!
// Generated by org/jetbrains/kotlin/generators/arguments/GenerateGradleOptions.kt
package org.jetbrains.kotlin.gradle.dsl

interface KotlinCommonToolOptions {

    /**
     * Report an error if there are any warnings
     * Default value: false
     */
     var allWarningsAsErrors: kotlin.Boolean

    /**
     * Generate no warnings
     * Default value: false
     */
     var suppressWarnings: kotlin.Boolean

    /**
     * Enable verbose logging output
     * Default value: false
     */
     var verbose: kotlin.Boolean

    /**
     * A list of additional compiler arguments
     * Default value: emptyList()
     */
     var freeCompilerArgs: kotlin.collections.List<kotlin.String>
}
