/*
 * Copyright 2010-2019 JetBrains s.r.o. and Kotlin Project contributors. Use of this source code is governed
 * by the Apache 2.0 license that can be found in the license/LICENSE.txt file.
 */

// DO NOT EDIT MANUALLY!
// Generated by org/jetbrains/kotlin/generators/arguments/GenerateGradleOptions.kt
package org.jetbrains.kotlin.gradle.dsl

interface KotlinCommonOptions  : org.jetbrains.kotlin.gradle.dsl.KotlinCommonToolOptions {

    /**
     * Allow to use declarations only from the specified version of bundled libraries
     * Possible values: "1.0", "1.1", "1.2", "1.3", "1.4 (EXPERIMENTAL)"
     * Default value: null
     */
     var apiVersion: kotlin.String?

    /**
     * Provide source compatibility with specified language version
     * Possible values: "1.0", "1.1", "1.2", "1.3", "1.4 (EXPERIMENTAL)"
     * Default value: null
     */
     var languageVersion: kotlin.String?
}
