/*
 * Copyright 2010-2019 JetBrains s.r.o. and Kotlin Project contributors. Use of this source code is governed
 * by the Apache 2.0 license that can be found in the license/LICENSE.txt file.
 */

// DO NOT EDIT MANUALLY!
// Generated by org/jetbrains/kotlin/generators/arguments/GenerateGradleOptions.kt
package org.jetbrains.kotlin.gradle.dsl

interface KotlinJsDceOptions  : org.jetbrains.kotlin.gradle.dsl.KotlinCommonToolOptions {

    /**
     * Development mode: don't strip out any code, just copy dependencies
     * Default value: false
     */
     var devMode: kotlin.Boolean

    /**
     * Output directory
     * Default value: null
     */
     var outputDirectory: kotlin.String?
}
